style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/relativityone/helm-charts
options:
  commit_groups:
    title_maps:
      build: Build ğŸ­
      chore: Maintenance ğŸ”§
      ci: Continuous Integration ğŸ’œ
      docs: Documentation ğŸ“˜
      feat: Features ğŸŒˆ
      fix: Bug Fixes ğŸ
      perf: Performance Improvements ğŸš€
      refactor: Code Refactoring ğŸ’
      revert: Revert Change â—€ï¸
      style: Code Style ğŸ¶
      test: Testing ğŸ’š
      sec: Security ğŸ›¡ï¸
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues:
    prefix:
      - DEVOPS-
  refs:
    actions:
      - Closes
  merges:
    pattern: "^Merge pull request '(\\w+)'$"
    pattern_maps:
      - Subject
  notes:
    keywords:
    - BREAKING CHANGE